name: phantom
channels:
  - conda-forge
  - nvidia
dependencies:
  - cuda-toolkit=12.1
  - python=3.10
  - pip:
    - ConfigArgParse==1.7.1
    - Cython==3.1.6
    - E2FGVI==0.0.1
    - Flask==3.1.2
    - Jinja2==3.1.6
    - Markdown==3.9
    - MarkupSafe==3.0.3
    - PyOpenGL==3.1.4
    - PySocks==1.7.1
    - PyYAML==6.0.3
    - Pygments==2.19.2
    - SAM-2==1.0
    - Send2Trash==1.8.3
    - Werkzeug==3.1.3
    - absl-py==2.3.1
    - addict==2.4.0
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.13.2
    - aiosignal==1.4.0
    - antlr4-python3-runtime==4.9.3
    - anyio==4.11.0
    - argon2-cffi==25.1.0
    - argon2-cffi-bindings==25.1.0
    - arrow==1.4.0
    - asttokens==3.0.0
    - async-lru==2.0.5
    - async-timeout==5.0.1
    - attrs==25.4.0
    - babel==2.17.0
    - beautifulsoup4==4.14.2
    - black==25.9.0
    - bleach==6.3.0
    - blinker==1.9.0
    - braceexpand==0.1.7
    - certifi==2025.10.5
    - cffi==2.0.0
    - charset-normalizer==3.4.4
    - chumpy==0.71
    - click==8.3.0
    - cloudpickle==3.1.1
    - colorlog==6.10.1
    - comm==0.2.3
    - contourpy==1.3.2
    - cycler==0.12.1
    - dash==3.2.0
    - debugpy==1.8.17
    - decorator==5.2.1
    - defusedxml==0.7.1
    - detectron2==0.6
    - diffusers==0.35.2
    - egl_probe==1.0.2
    - einops==0.8.1
    - epic-hand-object-detections==0.0.1
    - etils==1.13.0
    - eva-decord==0.6.1
    - evdev==1.9.2
    - exceptiongroup==1.3.0
    - executing==2.2.1
    - fastjsonschema==2.21.2
    - ffmpeg==1.4
    - filelock==3.20.0
    - fonttools==4.60.1
    - fqdn==1.5.1
    - freetype-py==2.5.1
    - frozenlist==1.8.0
    - fsspec==2025.9.0
    - fvcore==0.1.5.post20221221
    - gdown==5.2.0
    - glfw==2.10.0
    - grpcio==1.76.0
    - h11==0.16.0
    - h5py==3.15.1
    - hamer==0.0.0
    - hf-xet==1.2.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - huggingface-hub==0.36.0
    - hydra-colorlog==1.2.0
    - hydra-core==1.3.2
    - hydra-submitit-launcher==1.2.0
    - idna==3.11
    - imageio==2.37.0
    - imageio-ffmpeg==0.6.0
    - importlib_metadata==8.7.0
    - importlib_resources==6.5.2
    - iopath==0.1.9
    - ipykernel==7.1.0
    - ipython==8.37.0
    - ipywidgets==8.1.7
    - isoduration==20.11.0
    - itsdangerous==2.2.0
    - jedi==0.19.2
    - joblib==1.5.2
    - json-tricks==3.17.3
    - json5==0.12.1
    - jsonpointer==3.0.0
    - jsonschema==4.25.1
    - jsonschema-specifications==2025.9.1
    - jupyter==1.1.1
    - jupyter-console==6.6.3
    - jupyter-events==0.12.0
    - jupyter-lsp==2.3.0
    - jupyter_client==8.6.3
    - jupyter_core==5.9.1
    - jupyter_server==2.17.0
    - jupyter_server_terminals==0.5.3
    - jupyterlab==4.4.10
    - jupyterlab_pygments==0.3.0
    - jupyterlab_server==2.28.0
    - jupyterlab_widgets==3.0.15
    - kiwisolver==1.4.9
    - lark==1.3.1
    - lazy_loader==0.4
    - lightning-utilities==0.15.2
    - llvmlite==0.45.1
    - markdown-it-py==4.0.0
    - matplotlib==3.10.7
    - matplotlib-inline==0.2.1
    - mdurl==0.1.2
    - mediapy==1.2.4
    - mistune==3.1.4
    - mmcv==1.3.9
    - mmcv-full==1.7.2
    - mmpose==0.24.0
    - mpmath==1.3.0
    - mujoco==3.3.7
    - multidict==6.7.0
    - munkres==1.1.4
    - mypy_extensions==1.1.0
    - narwhals==2.10.0
    - nbclient==0.10.2
    - nbconvert==7.16.6
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - networkx==3.4.2
    - notebook==7.4.7
    - notebook_shim==0.2.4
    - numba==0.62.1
    - numpy==2.2.6
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-cufile-cu12==1.13.1.3
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-cusparselt-cu12==0.7.1
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.8.93
    - nvidia-nvshmem-cu12==3.3.20
    - nvidia-nvtx-cu12==12.1.105
    - omegaconf==2.3.0
    - open3d==0.19.0
    - opencv-python==4.12.0.88
    - overrides==7.7.0
    - packaging==25.0
    - pandas==2.3.3
    - pandocfilters==1.5.1
    - parso==0.8.5
    - pathspec==0.12.1
    - pexpect==4.9.0
    - phantom==0.1
    - pillow==12.0.0
    - platformdirs==4.5.0
    - plotly==6.3.1
    - portalocker==3.2.0
    - prometheus_client==0.23.1
    - prompt_toolkit==3.0.52
    - propcache==0.4.1
    - protobuf==3.20.0
    - psutil==7.1.2
    - ptyprocess==0.7.0
    - pure_eval==0.2.3
    - py-cpuinfo==9.0.0
    - pycocotools==2.0.10
    - pycparser==2.23
    - pyglet==2.1.9
    - pynput==1.8.1
    - pyparsing==3.2.5
    - pyquaternion==0.9.9
    - pyrender==0.1.45
    - pyrootutils==1.0.4
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.2.1
    - python-json-logger==4.0.0
    - python-xlib==0.33
    - pytokens==0.2.0
    - pytorch-lightning==2.5.5
    - pytz==2025.2
    - pyzed==5.0
    - pyzmq==27.1.0
    - referencing==0.37.0
    - regex==2025.10.23
    - requests==2.32.5
    - retrying==1.4.2
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rfc3987-syntax==1.1.0
    - rich==14.2.0
    - robomimic==0.3.0
    - robosuite==1.4.1
    - roma==1.5.4
    - rpds-py==0.28.0
    - rtree==1.4.1
    - safetensors==0.6.2
    - scikit-image==0.25.2
    - scikit-learn==1.7.2
    - scipy==1.15.3
    - seaborn==0.13.2
    - setuptools==80.9.0
    - shellingham==1.5.4
    - six==1.17.0
    - smplx==0.1.28
    - sniffio==1.3.1
    - soupsieve==2.8
    - stack-data==0.6.3
    - submitit==1.5.3
    - sympy==1.13.1
    - tabulate==0.9.0
    - tensorboard==2.20.0
    - tensorboard-data-server==0.7.2
    - tensorboardX==2.6.4
    - termcolor==3.2.0
    - terminado==0.18.1
    - thop==0.1.1-2209072238
    - threadpoolctl==3.6.0
    - tifffile==2025.5.10
    - timm==1.0.21
    - tinycss2==1.4.0
    - tokenizers==0.22.1
    - tomli==2.3.0
    - torch==2.5.1+cu121
    - torchmetrics==1.8.2
    - torchvision==0.20.1+cu121
    - tornado==6.5.2
    - tqdm==4.67.1
    - traitlets==5.14.3
    - transformers==4.57.1
    - trimesh==4.9.0
    - triton==3.1.0
    - typer-slim==0.20.0
    - typing_extensions==4.15.0
    - tzdata==2025.2
    - ultralytics==8.1.34
    - uri-template==1.3.0
    - urllib3==2.5.0
    - wcwidth==0.2.14
    - webcolors==24.11.1
    - webdataset==1.0.2
    - webencodings==0.5.1
    - websocket-client==1.9.0
    - widgetsnbextension==4.0.14
    - xtcocotools==1.14.3
    - yacs==0.1.8
    - yapf==0.43.0
    - yarl==1.22.0
    - zipp==3.23.0

prefix: "/home/dipam.modh/micromamba/envs/phantom"
