name: phantom
channels:
  - conda-forge
  - nvidia
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - absl-py=2.3.1=pyhd8ed1ab_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=py310h5541b7b_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alsa-lib=1.2.14=hb9d3cd8_0
  - aom=3.9.1=hac33072_0
  - assimp=5.4.3=hecf2907_1
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attr=2.5.2=h39aace5_0
  - attrs=25.4.0=pyh71513ae_0
  - binutils_impl_linux-64=2.44=h9d8b0ac_5
  - binutils_linux-64=2.44=h4852527_5
  - blinker=1.9.0=pyhff2d567_0
  - blosc=1.21.6=he440d0b_1
  - brotli=1.2.0=h41a2e66_0
  - brotli-bin=1.2.0=hf2c8021_0
  - brotli-python=1.2.0=py310h8cfb67f_0
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h3394656_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py310he7384ee_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - cli11=2.6.0=h54a6638_0
  - click=8.3.1=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.2=py310h3788b33_0
  - cuda-cccl_linux-64=12.9.27=0
  - cuda-command-line-tools=12.9.1=0
  - cuda-compiler=12.9.1=0
  - cuda-crt-dev_linux-64=12.9.86=0
  - cuda-crt-tools=12.9.86=0
  - cuda-cudart=12.9.79=0
  - cuda-cudart-dev=12.9.79=0
  - cuda-cudart-dev_linux-64=12.9.79=0
  - cuda-cudart-static=12.9.79=0
  - cuda-cudart-static_linux-64=12.9.79=0
  - cuda-cudart_linux-64=12.9.79=0
  - cuda-cuobjdump=12.9.82=1
  - cuda-cupti=12.9.79=0
  - cuda-cupti-dev=12.9.79=0
  - cuda-cuxxfilt=12.9.82=1
  - cuda-documentation=12.4.127=0
  - cuda-driver-dev=12.9.79=0
  - cuda-driver-dev_linux-64=12.9.79=0
  - cuda-gdb=12.9.79=1
  - cuda-libraries=12.9.1=0
  - cuda-libraries-dev=12.9.1=0
  - cuda-libraries-static=12.9.1=0
  - cuda-nsight=12.9.79=0
  - cuda-nvcc=12.9.86=0
  - cuda-nvcc-dev_linux-64=12.9.86=0
  - cuda-nvcc-impl=12.9.86=0
  - cuda-nvcc-tools=12.9.86=0
  - cuda-nvcc_linux-64=12.9.86=0
  - cuda-nvdisasm=12.9.88=1
  - cuda-nvml-dev=12.9.79=1
  - cuda-nvprof=12.9.79=0
  - cuda-nvprune=12.9.82=1
  - cuda-nvrtc=12.9.86=0
  - cuda-nvrtc-dev=12.9.86=0
  - cuda-nvrtc-static=12.9.86=0
  - cuda-nvtx=12.9.79=0
  - cuda-nvvm-dev_linux-64=12.9.86=0
  - cuda-nvvm-impl=12.9.86=0
  - cuda-nvvm-tools=12.9.86=0
  - cuda-nvvp=12.9.79=1
  - cuda-opencl=12.9.19=0
  - cuda-opencl-dev=12.9.19=0
  - cuda-profiler-api=12.9.79=0
  - cuda-sanitizer-api=12.9.79=1
  - cuda-toolkit=12.1.1=0
  - cuda-tools=12.9.1=0
  - cuda-version=12.9=3
  - cuda-visual-tools=12.9.1=0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dash=3.3.0=pyhd8ed1ab_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h3c4dab8_0
  - double-conversion=3.3.1=h5888daf_0
  - embree=4.4.0=ha751380_1
  - etils=1.12.2=pyhd8ed1ab_0
  - expat=2.7.1=hecca717_0
  - ffmpeg=8.0.0=gpl_h66263f8_506
  - flask=3.1.2=pyhd8ed1ab_0
  - fmt=11.2.0=h07f6e7f_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.60.1=py310h3406613_0
  - freeglut=3.2.2=ha6d2627_3
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - frozenlist=1.7.0=py310h9548a50_0
  - fsspec=2025.10.0=pyhd8ed1ab_0
  - gcc_impl_linux-64=13.4.0=h69c5793_7
  - gcc_linux-64=13.4.0=h0a5b801_12
  - gdk-pixbuf=2.44.4=h2b0a6b4_0
  - gds-tools=1.14.1.1=4
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - gl2ps=1.4.2=hae5d5c5_1
  - glew=2.2.0=h3abd4de_0
  - glfw=3.4=hb03c661_1
  - glslang=16.0.0=hfd11570_0
  - gmp=6.3.0=hac33072_2
  - graphite2=1.3.14=hecca717_2
  - gxx_impl_linux-64=13.4.0=haf17267_7
  - gxx_linux-64=13.4.0=hb5b9838_12
  - h2=4.3.0=pyhcf101f3_0
  - h5py=3.15.1=nompi_py310h4aa865e_100
  - harfbuzz=12.2.0=h15599e2_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.6=nompi_h6e4c0c1_103
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.11=pyhd8ed1ab_0
  - imath=3.2.2=hde8ca8f_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - intel-gmmlib=22.8.2=hb700be7_0
  - intel-media-driver=25.3.4=hecca717_0
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jasper=4.2.8=he3c4edf_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - jsoncpp=1.9.6=hf42df4d_1
  - kernel-headers_linux-64=5.14.0=he073ed8_2
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py310haaf941d_2
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h1aa0949_5
  - lerc=4.0.0=h0aef613_1
  - level-zero=1.26.0=hb700be7_0
  - libabseil=20250512.1=cxx17_hba17884_0
  - libaec=1.1.4=h3f801dc_0
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libass=0.17.4=h96ad9f0_0
  - libavif16=1.3.0=h6395336_2
  - libblas=3.11.0=1_h4a7cf45_openblas
  - libboost=1.88.0=hed09d94_6
  - libbrotlicommon=1.2.0=h09219d5_0
  - libbrotlidec=1.2.0=hd53d788_0
  - libbrotlienc=1.2.0=h02bd7ab_0
  - libcap=2.77=h3ff7636_0
  - libcblas=3.11.0=1_h0358290_openblas
  - libccd-double=2.1=h59595ed_3
  - libclang-cpp21.1=21.1.5=default_h99862b1_1
  - libclang13=21.1.5=default_h746c552_1
  - libcublas=12.9.1.4=0
  - libcublas-dev=12.9.1.4=0
  - libcublas-static=12.9.1.4=0
  - libcufft=11.4.1.4=0
  - libcufft-dev=11.4.1.4=0
  - libcufft-static=11.4.1.4=0
  - libcufile=1.14.1.1=4
  - libcufile-dev=1.14.1.1=4
  - libcufile-static=1.14.1.1=4
  - libcups=2.3.3=hb8b1518_5
  - libcurand=10.3.10.19=0
  - libcurand-dev=10.3.10.19=0
  - libcurand-static=10.3.10.19=0
  - libcurl=8.17.0=h4e3cde8_0
  - libcusolver=11.7.5.82=0
  - libcusolver-dev=11.7.5.82=0
  - libcusolver-static=11.7.5.82=0
  - libcusparse=12.5.10.65=0
  - libcusparse-dev=12.5.10.65=0
  - libcusparse-static=12.5.10.65=0
  - libdeflate=1.25=h17f619e_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libflac=1.4.3=h59595ed_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-devel_linux-64=13.4.0=hba01cd7_107
  - libgcc-ng=15.2.0=h69a702a_7
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.1=h32235b2_2
  - libglu=9.0.3=h5888daf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h767d61c_7
  - libhwloc=2.12.1=default_h7f8ec31_1002
  - libhwy=1.3.0=h4c17acf_1
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - libjxl=0.11.1=hf08fa70_5
  - liblapack=3.11.0=1_h47877c9_openblas
  - liblapacke=3.11.0=1_h6ae95b6_openblas
  - libllvm21=21.1.5=hf7376ad_0
  - liblzf=3.6=hb9d3cd8_3
  - liblzma=5.8.1=hb9d3cd8_2
  - libmujoco=3.3.7=h31df9c7_0
  - libnetcdf=4.9.3=nompi_h11f7409_103
  - libnghttp2=1.67.0=had1ee68_0
  - libnpp=12.4.1.87=0
  - libnpp-dev=12.4.1.87=0
  - libnpp-static=12.4.1.87=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libnvfatbin=12.9.82=0
  - libnvfatbin-dev=12.9.82=0
  - libnvfatbin-static=12.9.82=0
  - libnvjitlink=12.9.86=0
  - libnvjitlink-dev=12.9.86=0
  - libnvjitlink-static=12.9.86=0
  - libnvjpeg=12.4.0.76=0
  - libnvjpeg-dev=12.4.0.76=0
  - libnvjpeg-static=12.4.0.76=0
  - libnvvm-samples=12.1.105=0
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopencv=4.12.0=qt6_py310hdb0ca46_607
  - libopengl=1.7.0=ha4b6fd6_2
  - libopengl-devel=1.7.0=ha4b6fd6_2
  - libopenvino=2025.2.0=hb617929_1
  - libopenvino-auto-batch-plugin=2025.2.0=hed573e4_1
  - libopenvino-auto-plugin=2025.2.0=hed573e4_1
  - libopenvino-hetero-plugin=2025.2.0=hd41364c_1
  - libopenvino-intel-cpu-plugin=2025.2.0=hb617929_1
  - libopenvino-intel-gpu-plugin=2025.2.0=hb617929_1
  - libopenvino-intel-npu-plugin=2025.2.0=hb617929_1
  - libopenvino-ir-frontend=2025.2.0=hd41364c_1
  - libopenvino-onnx-frontend=2025.2.0=h1862bb8_1
  - libopenvino-paddle-frontend=2025.2.0=h1862bb8_1
  - libopenvino-pytorch-frontend=2025.2.0=hecca717_1
  - libopenvino-tensorflow-frontend=2025.2.0=h0767aad_1
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hecca717_1
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - libpq=18.0=h3675c94_0
  - libprotobuf=6.31.1=h49aed37_2
  - librsvg=2.60.0=h61e6d4b_0
  - libsanitizer=13.4.0=h14bf0c3_7
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.51.0=hee844dc_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-devel_linux-64=13.4.0=hba01cd7_107
  - libstdcxx-ng=15.2.0=h4852527_7
  - libsystemd0=258.2=h6569c3e_1
  - libtheora=1.1.1=h4ab18f5_1006
  - libtiff=4.7.1=h9d88235_1
  - libudev1=258.2=h6569c3e_1
  - libunwind=1.8.3=h65a8314_0
  - liburing=2.12=hb700be7_0
  - libusb=1.0.29=h73b1eb8_0
  - libuuid=2.41.2=he9a06e4_0
  - libva=2.22.0=h4f16b4b_2
  - libvorbis=1.3.7=h54a6638_2
  - libvpl=2.15.0=h54a6638_1
  - libvpx=1.14.1=hac33072_0
  - libvulkan-loader=1.4.328.1=h5279c79_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.13.0=hca5e8e5_0
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lodepng=20220109=h924138e_0
  - loguru=0.7.3=pyh707e725_0
  - lz4-c=1.10.0=h5888daf_1
  - markupsafe=3.0.3=py310h3406613_0
  - matplotlib-base=3.10.8=py310hfde16b3_0
  - mpg123=1.32.9=hc50e24c_0
  - msgpack-python=1.1.2=py310h03d9f68_1
  - mujoco=3.3.7=hf605be5_0
  - mujoco-python=3.3.7=np2py310h52bcc57_0
  - mujoco-samples=3.3.7=h9273d1a_0
  - mujoco-simulate=3.3.7=h9273d1a_0
  - multidict=6.6.3=py310h89163eb_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - narwhals=2.12.0=pyhcf101f3_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nlohmann_json=3.12.0=h54a6638_1
  - nsight-compute=2025.2.1.3=0
  - nspr=4.38=h29cc59b_0
  - nss=3.117=h445c969_0
  - numpy=2.2.6=py310hefbff90_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - opencv=4.12.0=qt6_py310hec850f8_607
  - openexr=3.4.3=he10986b_0
  - openh264=2.6.0=hc22cd8d_0
  - openjpeg=2.5.4=h55fea9a_0
  - openjph=0.25.3=h8d634f6_0
  - openldap=2.6.10=he970967_0
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py310h0158d43_1
  - pango=1.56.4=hadf4263_0
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.46=h1321c63_0
  - pillow=12.0.0=py310h80abafc_0
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - plotly=6.5.0=pyhd8ed1ab_0
  - proj=9.7.0=hb72c0af_0
  - propcache=0.3.1=py310h89163eb_0
  - psutil=7.1.3=py310h139afa4_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pugixml=1.15=h3f63f65_0
  - pulseaudio-client=17.0=h9a6aba3_3
  - py-cpuinfo=9.0.0=pyhd8ed1ab_1
  - py-opencv=4.12.0=qt6_py310h89973df_607
  - pybind11-abi=11=hc364b38_1
  - pycparser=2.22=pyh29332c3_1
  - pyglfw=2.10.0=pyha770c72_0
  - pyopengl=3.1.10=pyha804496_2
  - pyopengl-accelerate=3.1.10=py310hf779ad0_1
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.19=h3c07f61_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py310h3406613_0
  - qhull=2020.2=h434a139_5
  - qt6-main=6.9.3=h5c1c036_1
  - rav1e=0.7.1=h8fae777_3
  - readline=8.2=h8c095d6_2
  - requests=2.32.5=pyhd8ed1ab_0
  - retrying=1.4.2=pyhe01879c_0
  - scikit-learn=1.7.2=py310h228f341_0
  - scipy=1.15.2=py310h1d65ade_0
  - sdl2=2.32.56=h54a6638_0
  - sdl3=3.2.26=h68140b3_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.9.0=pyhff2d567_0
  - shaderc=2025.4=h3e344bc_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_1
  - spirv-tools=2025.4=hb700be7_0
  - sqlite=3.51.0=heff268d_0
  - statsmodels=0.14.5=py310hf779ad0_1
  - svt-av1=3.1.2=hecca717_0
  - sysroot_linux-64=2.34=h087de78_2
  - tbb=2022.3.0=h8d10470_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinyobjloader=1.0.7=h59595ed_2
  - tinyxml2=11.0.0=h3f2d84a_0
  - tk=8.6.13=noxft_hd72426e_102
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - ultralytics=8.1.34=pyh2965483_0
  - unicodedata2=17.0.0=py310h7c4b9e2_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - utfcpp=4.0.8=ha770c72_0
  - vtk-base=9.5.1=py310h991dc19_7
  - wayland=1.24.0=hd6090a7_1
  - wayland-protocols=1.45=hd8ed1ab_0
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - wslink=2.5.0=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.6=hb03c661_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxinerama=1.1.5=h5888daf_1
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxscrnsaver=1.2.4=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - yaml=0.2.5=h280c20c_3
  - yarl=1.22.0=py310h3406613_0
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.2.5=hde8ca8f_0
  - zstandard=0.25.0=py310h139afa4_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
    - ConfigArgParse==1.7.1
    - Cython==3.2.1
    - E2FGVI==0.0.1
    - ImageIO==2.37.2
    - Markdown==3.10
    - PyOpenGL==3.1.0
    - Pygments==2.19.2
    - SAM-2==1.0
    - Send2Trash==1.8.3
    - addict==2.4.0
    - antlr4-python3-runtime==4.9.3
    - anyio==4.11.0
    - argon2-cffi==25.1.0
    - argon2-cffi-bindings==25.1.0
    - arrow==1.4.0
    - asttokens==3.0.0
    - async-lru==2.0.5
    - babel==2.17.0
    - beautifulsoup4==4.14.2
    - black==25.11.0
    - bleach==6.3.0
    - braceexpand==0.1.7
    - chumpy==0.71
    - cloudpickle==3.1.2
    - colorlog==6.10.1
    - comm==0.2.3
    - contourpy==1.3.2
    - cycler==0.12.1
    - debugpy==1.8.17
    - decorator==5.2.1
    - defusedxml==0.7.1
    - detectron2==0.6
    - diffusers==0.35.2
    - egl_probe==1.0.2
    - einops==0.8.1
    - eva-decord==0.6.1
    - evdev==1.9.2
    - exceptiongroup==1.3.0
    - executing==2.2.1
    - fastjsonschema==2.21.2
    - filelock==3.20.0
    - fonttools==4.60.1
    - fqdn==1.5.1
    - freetype-py==2.5.1
    - fvcore==0.1.5.post20221221
    - gdown==5.2.0
    - grpcio==1.76.0
    - h11==0.16.0
    - hamer==0.0.0
    - hf-xet==1.2.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - huggingface-hub==0.36.0
    - hydra-colorlog==1.2.0
    - hydra-core==1.3.2
    - hydra-submitit-launcher==1.2.0
    - imageio-ffmpeg==0.6.0
    - iopath==0.1.9
    - ipykernel==7.1.0
    - ipython==8.37.0
    - ipywidgets==8.1.8
    - isoduration==20.11.0
    - jedi==0.19.2
    - json5==0.12.1
    - jsonpointer==3.0.0
    - jsonschema==4.25.1
    - jsonschema-specifications==2025.9.1
    - jupyter==1.1.1
    - jupyter-console==6.6.3
    - jupyter-events==0.12.0
    - jupyter-lsp==2.3.0
    - jupyter_client==8.6.3
    - jupyter_core==5.9.1
    - jupyter_server==2.17.0
    - jupyter_server_terminals==0.5.3
    - jupyterlab==4.4.10
    - jupyterlab_pygments==0.3.0
    - jupyterlab_server==2.28.0
    - jupyterlab_widgets==3.0.16
    - kiwisolver==1.4.9
    - lark==1.3.1
    - lazy_loader==0.4
    - lightning-utilities==0.15.2
    - llvmlite==0.45.1
    - markdown-it-py==4.0.0
    - matplotlib==3.10.7
    - matplotlib-inline==0.2.1
    - mdurl==0.1.2
    - mediapy==1.2.4
    - mistune==3.1.4
    - mmcv==2.2.0
    - mmcv-full==1.7.2
    - mmengine==0.10.7
    - mpmath==1.3.0
    - mypy_extensions==1.1.0
    - nbclient==0.10.2
    - nbconvert==7.16.6
    - nbformat==5.10.4
    - networkx==3.4.2
    - notebook==7.4.7
    - notebook_shim==0.2.4
    - numba==0.62.1
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-cufile-cu12==1.13.1.3
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-cusparselt-cu12==0.7.1
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.8.93
    - nvidia-nvshmem-cu12==3.3.20
    - nvidia-nvtx-cu12==12.1.105
    - omegaconf==2.3.0
    - open3d==0.19.0
    - opencv-python==4.12.0.88
    - overrides==7.7.0
    - packaging==25.0
    - pandocfilters==1.5.1
    - parso==0.8.5
    - pathspec==0.12.1
    - pexpect==4.9.0
    - phantom==0.1
    - pillow==12.0.0
    - platformdirs==4.5.0
    - portalocker==3.2.0
    - prometheus_client==0.23.1
    - prompt_toolkit==3.0.52
    - protobuf==6.33.1
    - ptyprocess==0.7.0
    - pure_eval==0.2.3
    - pycocotools==2.0.10
    - pyglet==2.1.11
    - pynput==1.8.1
    - pyparsing==3.2.5
    - pyquaternion==0.9.9
    - pyrender==0.1.45
    - pyrootutils==1.0.4
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.2.1
    - python-json-logger==4.0.0
    - python-xlib==0.33
    - pytokens==0.3.0
    - pytorch-lightning==2.5.6
    - pyzmq==27.1.0
    - referencing==0.37.0
    - regex==2025.11.3
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rfc3987-syntax==1.1.0
    - rich==14.2.0
    - robomimic==0.3.0
    - robosuite==1.4.1
    - rpds-py==0.28.0
    - safetensors==0.6.2
    - scikit-image==0.25.2
    - setuptools==80.9.0
    - six==1.17.0
    - smplx==0.1.28
    - sniffio==1.3.1
    - soupsieve==2.8
    - stack-data==0.6.3
    - submitit==1.5.3
    - sympy==1.13.1
    - tabulate==0.9.0
    - tensorboard==2.20.0
    - tensorboard-data-server==0.7.2
    - tensorboardX==2.6.4
    - termcolor==3.2.0
    - terminado==0.18.1
    - tifffile==2025.5.10
    - timm==1.0.22
    - tinycss2==1.4.0
    - tokenizers==0.19.1
    - tomli==2.3.0
    - torch==2.5.1+cu121
    - torchmetrics==1.8.2
    - torchvision==0.20.1+cu121
    - tornado==6.5.2
    - traitlets==5.14.3
    - transformers==4.42.1
    - trimesh==4.9.0
    - triton==3.1.0
    - uri-template==1.3.0
    - wcwidth==0.2.14
    - webcolors==25.10.0
    - webdataset==1.0.2
    - webencodings==0.5.1
    - websocket-client==1.9.0
    - widgetsnbextension==4.0.15
    - xtcocotools==1.14.3
    - yacs==0.1.8
    - yapf==0.43.0

prefix: "/home/dipam.modh/micromamba/envs/phantom"
